name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CC: clang
      CXX: clang++

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: CMake and Clang versions
        run: |
          cmake --version
          $CC --version
          $CXX --version

      - name: Configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --parallel

      - name: Bench
        working-directory: build
        run: ./Moraband bench | tee bench.txt
      
      - name: Create zip artifact
        working-directory: build
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          zip Moraband-v1.2-Linux-${SHORT_SHA}.zip Moraband bench.txt
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: Moraband-Linux-artifact
          path: build/Moraband-v1.2-Linux-${{ env.SHORT_SHA }}.zip

      - name: Post results
        if: github.event_name == 'pull_request'
        run: |
          tail -n 3 build/bench.txt | grep -q "^Time:" && \
          tail -n 3 build/bench.txt | grep -q "^Nodes:" && \
          tail -n 3 build/bench.txt | grep -q "^NPS:" && \
          gh pr comment "$PR_URL" --body <(tail -n 3 build/bench.txt) || \
          echo "Bench results invalid or missing, skipping comment"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
