name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CC: clang
      CXX: clang++

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: CMake and Clang versions
        run: |
          cmake --version
          $CC --version
          $CXX --version

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
      
      - name: Bench
        working-directory: build
        run: ./Moraband bench | tee ../bench.txt
      
      - name: Upload bench output
        uses: actions/upload-artifact@v4
        with:
          name: bench
          path: bench.txt

      - name: Post results
        if: github.event_name == 'pull_request'
        run: |
          tail -n 3 bench.txt > results.txt
          if grep -q "^Time:" results.txt && grep -q "^Nodes:" results.txt && grep -q "^NPS:" results.txt; then
            echo "Bench results valid, posting comment"
            gh pr comment "$PR_URL" --body-file results.txt
          else
            echo "Bench results invalid or missing, skipping comment"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
